#:schema node_modules/wrangler/config-schema.json
name = "1111"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "3655cfee485740ebad29bc72882658d7" }
]

[assets]
directory = "./public"
